apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sentryflow-pre-deletion-cleanup
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "patch"]
  - apiGroups: ["networking.istio.io"]
    resources: ["envoyfilters"]
    verbs: ["get", "delete"]
  - apiGroups: ["extensions.istio.io"]
    resources: ["wasmplugins"]
    verbs: ["get", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentryflow-pre-deletion-cleanup
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sentryflow-pre-deletion-cleanup
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sentryflow-pre-deletion-cleanup
subjects:
  - kind: ServiceAccount
    name: sentryflow-pre-deletion-cleanup
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sentryflow-pre-deletion-cleanup
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: sentryflow-pre-deletion-cleanup
      restartPolicy: Never
      containers:
        - name: pre-deletion-cleanup
          image: "bitnami/kubectl:1.30"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
                set -e
                echo "Scaling down SentryFlow deployment..."
                kubectl -n {{ .Release.Namespace }} scale deploy {{ include "sentryflow.fullname" . }} --replicas=0 || true

                echo "Deleting EnvoyFilter http-filter..."
                kubectl -n istio-system delete envoyfilter http-filter --ignore-not-found=true

                echo "Deleting WasmPlugin http-filter..."
                kubectl -n istio-system delete wasmplugin http-filter --ignore-not-found=true

                echo "Cleanup complete."
