apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: http-filter-gateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  failStrategy: FAIL_OPEN
  priority: 100
  pluginConfig:
    upstream_name: sentryflow
    api_path: /api/v1/events
    authority: sentryflow
  url: public.ecr.aws/k9v9d5v2/sentryflow-httpfilter:v0.4-gateway
