name: "Docker image build scan and push"
description: "Composite workflow to build scan and push docker images"
inputs:
  docker_context:
    required: false
    description: "Docker context path to use"
    default: "."
  dockerfile_path:
    required: false
    description: "file path"
    default: "./Dockerfile"
  docker_build_args:
    required: false
    description: "Additional arguments passed to docker build"
  image_name:
    description: "Image name"
    required: true
  repository_name:
    description: "Container repository name"
    required: true
  tag:
    description: "Add version tag to the repository"
    required: true
    default: "${{ github.run_id }}"
  registry_type:
    required: false
    description: "Repo type"
    default: private
  cspm_endpoint:
    description: "The URL of the CSPM panel to push the scan results to."
    required: false
    default: "cspm.accuknox.com"
  cspm_token:
    description: "The token for authenticating with the CSPM panel."
    required: false
  tenant_id:
    description: "The ID of the tenant associated with the CSPM panel."
    required: false
  severity:
    description: "Allows selection of severity level for the scan. Options include UNKNOWN, LOW, MEDIUM, HIGH, CRITICAL. If specified, the scan will target vulnerabilities of the selected severity level."
    required: false
    default: "HIGH,CRITICAL"
  exit_code:
    description: "Values '0' and '1' are accepted. '0' is the default value, which indicates that the pipeline will not be halted if the specified severity is found, while '1' indicates that the pipeline will stop if a specified severity level is detected."
    required: false
    default: "1"
  ignore_unfixed:
    description: "Ignore vulnerabilities for which a fix isn't available yet."
    required: false
    default: true
  label:
    description: "The label created in AccuKnox SaaS for associating scan results."
    required: false
  disable_scan:
    description: "Skip scanning the container image"
    required: false
    default: false

runs:
  using: composite
  steps:
  - name: Docker build
    uses: accuknox/common-gh-actions/actions/docker-build@main
    id: docker-build
    with:
      docker-context: ${{ inputs.docker_context }}
      file-path: ${{ inputs.dockerfile_path }}
      tag: ${{ inputs.tag }}
      image-name: ${{ inputs.image_name }}
      repo: ${{ inputs.repository_name }}
      args: ${{ inputs.docker_build_args }}

  # - name: Run Trivy vulnerability scanner
  #   uses: accuknox/common-gh-actions/actions/container-scan@main
  #   id: trivy-scan
  #   if: ${{ inputs.disable_scan == 'false' }}
  #   with:
  #     endpoint: ${{ inputs.cspm_endpoint }}
  #     token: ${{ inputs.cspm_token }}
  #     tenant_id: ${{ inputs.tenant_id }}
  #     repository_name: ${{ inputs.repository_name }}/${{ inputs.image_name }}
  #     tag: ${{ inputs.tag }}
  #     severity: ${{ inputs.severity }}
  #     exit_code: ${{ inputs.exit_code }}
  #     ignore_unfixed: ${{ inputs.ignore_unfixed }}
  #     label: ${{ inputs.label }}

  - name: Login to ECR
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v2
    with:
      registry-type: ${{ inputs.registry_type }}

  - name: Docker push to ECR
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    shell: bash
    run: docker push ${{ inputs.repository_name }}/${{ inputs.image_name }}:${{ inputs.tag }}